// Formation configurations with coordinate percentages (top%, left%)
// Each position has: id, position label, top (y-axis %), left (x-axis %)

export const FORMATIONS = {
  '4-4-2': {
    name: '4-4-2',
    positions: [
      { id: 'gk', position: 'GK', top: 90, left: 50 },
      { id: 'lb', position: 'LB', top: 70, left: 15 },
      { id: 'lcb', position: 'CB', top: 75, left: 37 },
      { id: 'rcb', position: 'CB', top: 75, left: 63 },
      { id: 'rb', position: 'RB', top: 70, left: 85 },
      { id: 'lm', position: 'LM', top: 45, left: 15 },
      { id: 'lcm', position: 'CM', top: 50, left: 37 },
      { id: 'rcm', position: 'CM', top: 50, left: 63 },
      { id: 'rm', position: 'RM', top: 45, left: 85 },
      { id: 'lst', position: 'ST', top: 15, left: 37 },
      { id: 'rst', position: 'ST', top: 15, left: 63 },
    ],
  },
  '4-3-3': {
    name: '4-3-3',
    positions: [
      { id: 'gk', position: 'GK', top: 90, left: 50 },
      { id: 'lb', position: 'LB', top: 70, left: 15 },
      { id: 'lcb', position: 'CB', top: 75, left: 37 },
      { id: 'rcb', position: 'CB', top: 75, left: 63 },
      { id: 'rb', position: 'RB', top: 70, left: 85 },
      { id: 'lcm', position: 'CM', top: 50, left: 25 },
      { id: 'cm', position: 'CM', top: 45, left: 50 },
      { id: 'rcm', position: 'CM', top: 50, left: 75 },
      { id: 'lw', position: 'LW', top: 20, left: 15 },
      { id: 'st', position: 'ST', top: 15, left: 50 },
      { id: 'rw', position: 'RW', top: 20, left: 85 },
    ],
  },
  '4-2-3-1': {
    name: '4-2-3-1',
    positions: [
      { id: 'gk', position: 'GK', top: 90, left: 50 },
      { id: 'lb', position: 'LB', top: 70, left: 15 },
      { id: 'lcb', position: 'CB', top: 75, left: 37 },
      { id: 'rcb', position: 'CB', top: 75, left: 63 },
      { id: 'rb', position: 'RB', top: 70, left: 85 },
      { id: 'lcdm', position: 'CDM', top: 55, left: 37 },
      { id: 'rcdm', position: 'CDM', top: 55, left: 63 },
      { id: 'lam', position: 'LAM', top: 30, left: 20 },
      { id: 'cam', position: 'CAM', top: 28, left: 50 },
      { id: 'ram', position: 'RAM', top: 30, left: 80 },
      { id: 'st', position: 'ST', top: 10, left: 50 },
    ],
  },
  '3-5-2': {
    name: '3-5-2',
    positions: [
      { id: 'gk', position: 'GK', top: 90, left: 50 },
      { id: 'lcb', position: 'CB', top: 75, left: 25 },
      { id: 'cb', position: 'CB', top: 78, left: 50 },
      { id: 'rcb', position: 'CB', top: 75, left: 75 },
      { id: 'lwb', position: 'LWB', top: 55, left: 10 },
      { id: 'lcm', position: 'CM', top: 50, left: 30 },
      { id: 'cm', position: 'CM', top: 45, left: 50 },
      { id: 'rcm', position: 'CM', top: 50, left: 70 },
      { id: 'rwb', position: 'RWB', top: 55, left: 90 },
      { id: 'lst', position: 'ST', top: 15, left: 37 },
      { id: 'rst', position: 'ST', top: 15, left: 63 },
    ],
  },
  '3-4-3': {
    name: '3-4-3',
    positions: [
      { id: 'gk', position: 'GK', top: 90, left: 50 },
      { id: 'lcb', position: 'CB', top: 75, left: 25 },
      { id: 'cb', position: 'CB', top: 78, left: 50 },
      { id: 'rcb', position: 'CB', top: 75, left: 75 },
      { id: 'lm', position: 'LM', top: 50, left: 15 },
      { id: 'lcm', position: 'CM', top: 50, left: 40 },
      { id: 'rcm', position: 'CM', top: 50, left: 60 },
      { id: 'rm', position: 'RM', top: 50, left: 85 },
      { id: 'lw', position: 'LW', top: 20, left: 15 },
      { id: 'st', position: 'ST', top: 15, left: 50 },
      { id: 'rw', position: 'RW', top: 20, left: 85 },
    ],
  },
  '5-3-2': {
    name: '5-3-2',
    positions: [
      { id: 'gk', position: 'GK', top: 90, left: 50 },
      { id: 'lwb', position: 'LWB', top: 70, left: 10 },
      { id: 'lcb', position: 'CB', top: 75, left: 30 },
      { id: 'cb', position: 'CB', top: 78, left: 50 },
      { id: 'rcb', position: 'CB', top: 75, left: 70 },
      { id: 'rwb', position: 'RWB', top: 70, left: 90 },
      { id: 'lcm', position: 'CM', top: 45, left: 30 },
      { id: 'cm', position: 'CM', top: 42, left: 50 },
      { id: 'rcm', position: 'CM', top: 45, left: 70 },
      { id: 'lst', position: 'ST', top: 15, left: 37 },
      { id: 'rst', position: 'ST', top: 15, left: 63 },
    ],
  },
  '4-1-4-1': {
    name: '4-1-4-1',
    positions: [
      { id: 'gk', position: 'GK', top: 90, left: 50 },
      { id: 'lb', position: 'LB', top: 70, left: 15 },
      { id: 'lcb', position: 'CB', top: 75, left: 37 },
      { id: 'rcb', position: 'CB', top: 75, left: 63 },
      { id: 'rb', position: 'RB', top: 70, left: 85 },
      { id: 'cdm', position: 'CDM', top: 55, left: 50 },
      { id: 'lm', position: 'LM', top: 38, left: 15 },
      { id: 'lcm', position: 'CM', top: 35, left: 37 },
      { id: 'rcm', position: 'CM', top: 35, left: 63 },
      { id: 'rm', position: 'RM', top: 38, left: 85 },
      { id: 'st', position: 'ST', top: 10, left: 50 },
    ],
  },
}

export const KIT_COLORS = [
  { name: 'Red', value: '#EF4444' },
  { name: 'Blue', value: '#3B82F6' },
  { name: 'White', value: '#FFFFFF' },
  { name: 'Black', value: '#1F2937' },
  { name: 'Orange', value: '#F97316' },
  { name: 'Green', value: '#22C55E' },
  { name: 'Yellow', value: '#EAB308' },
  { name: 'Purple', value: '#A855F7' },
]

export const DEFAULT_KIT_COLOR = '#3B82F6' // Blue
